name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v1
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and export to Docker client
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./src/api/IoT-Architectures.Api/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: brammys/iot-architectures
