version: "3.9"
services:
  iot-architectures:
    container_name: iot-architectures
    restart: unless-stopped
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      mongodb:
        condition: service_started
    volumes:
      - $APPDATA/Microsoft/UserSecrets/aa304482-ff10-4c6d-b8c5-fa8ab4eda262:/root/.microsoft/usersecrets/aa304482-ff10-4c6d-b8c5-fa8ab4eda262 # Windows host
      #- $HOME/.microsoft/usersecrets/aa304482-ff10-4c6d-b8c5-fa8ab4eda262:/root/.microsoft/usersecrets/aa304482-ff10-4c6d-b8c5-fa8ab4eda262 # Linux / Mac hosts
    build:
      context: ../
      dockerfile: ./src/api/IoT-Architectures.Api/Dockerfile
    networks:
      - api
      - database

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - database

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=REPLACE_WITH_TOKEN
    networks:
      - api

networks:
  database:
  api: